kind: ConfigMap
apiVersion: v1
metadata:
  name: st-no-wf-nginx-config
data:
  nginx.conf: |
    events {
    }
    http {
      include /etc/nginx/mime.types;
    
      server {
        add_header Access-Control-Allow-Origin *;
        client_max_body_size 10M;
    
        server_name product-webfront.noto-data.com ;
        root /usr/share/nginx/html/;
    
        listen 80 default_server;
        listen [::]:80 default_server;

        location / {
          index index.html;
          try_files $uri $uri/ /index.html;
        }
      }
    }
